### PR TITLE
Add UnitTestContainer capability

### PR DESCRIPTION
**Pull request by tmat**
See https://github.com/dotnet/testimpact/issues/1119 for details.

### CODE REVIEW

**Comment by tmat** [comment]
@srivatsn

**Comment by srivatsn** [comment]
@lifengl @jviau

**Comment by adrianvmsft** [comment]
👍

**Comment by tmat** [comment]
@srivatsn Could you merge for me please? I don't seem to be allowed to do that.

**Comment by srivatsn** [comment]
I don't have permissions either. @adrianvmsft or @lifengl?

**Pull request merged**
