### PR TITLE
Cleaning up the CPS_Core_vs._CPS_VS.md topic

### PR DESCRIPTION
**Pull request by gusper**
One thing I'm not sure of is why there were so many spaces interspersed in the middle of sentences. The changes in this PR get rid of them as I couldn't see any downsides to doing so but figured I'd mention it just in case.

### CODE REVIEW

**Comment by AArnott** [comment]
What were you looking at when you saw all those extra spaces? The [raw markdown text](https://raw.githubusercontent.com/Microsoft/VSProjectSystem/master/doc/overview/CPS_Core_vs._CPS_VS.md) or the [rendered HTML on GitHub](https://github.com/Microsoft/VSProjectSystem/blob/master/doc/overview/CPS_Core_vs._CPS_VS.md)?

MarkDown is supposed to look good in either view, but especially when rendered as HTML. I don't see a bunch of extra spaces in the middle of sentences in either view, actually. But we do take care to try to keep lines short, so we have line feeds at around 80 characters, consistent with some folks' preferences for markdown. Other than a narrow column then where are the extra spaces? 

Since your pull request eliminates all the extra line feeds we added to keep lines short, I'm not sure we can take this unless we decide to change our policy.

**Comment by AArnott** [comment]
But I do like some of the changes you made like the added like and capitalization changes. If you can revert the other changes but keep those, I'd like to take that pull request. :+1: 

Pro tip: for reasons such as these and others, github pull requests are generally *highly focused*. Mixing formatting changes with real text changes is generally discouraged. It's better to send one pull request with the real text changes, then a subsequent one that claims to change nothing significant, just whitespace.

**Comment by gusper** [comment]
Okay, it's the linefeeds I didn't know about and I now understand what I did. I'll get it correct a little later and resubmit.Thanks for the info though, helpful.

**Comment by gusper** [comment]
Okay, I think it meets the formatting guidelines now. Let me know if there's something else I'm missing. Thanks!

**Comment by AArnott** [comment]
:+1: Thanks!

**Pull request merged**
