### PR TITLE
Single file generators

### PR DESCRIPTION
**Pull request by adrianvmsft**
looks good

### CODE REVIEW

**Comment by dazinator** [comment]
Great stuff, thank you very much for these docs, it does make sense. 
I have noted one slight difference in my own scenario compared to the documented one, and that is i need the generator to be set on an existing / well known file extension -".ascx" files, which I am adding with my own item template. After reading this I believe it will be the rule, not the item template, that is responsible for setting the "generator" property so the item template should be largely irrelevant. So my only concern is that i'm hoping i don't hit some sort of scenario where there is already some conflicting rule defined for ".ascx" files imported by CPS that I can't override in order to extend with this "generator" property. That's a different issue though and i'll find out soon enough :)
Cheers

**Comment by adrianvmsft** [comment]
@dazinator If you run into problems overriding the rule, please apply the workaround specified in #81 (revert the import order of the 2 targets).
Thanks!
Adrian

**Comment by jviau** [comment]
Looks good. :shipit:

**Comment by dazinator** [comment]
I _finally_ got around to trying this out today. For some reason, my single file generator isn't being loaded or invoked though - leaving me a bit stumped!

My project item looks good:

image

However when I save changes to the file, nothing happens. Breakpoint in my single file generator's constructor or `GenerateCode` method is never hit.

If I click the "edit" button next to the custom tool property:

image

So it suggest the custom tool can't be loaded or isn't registered correctly?

Nothing useful in the output window. 

Any ideas how I can work through this issue? Are there some potentially useful log files somewhere I can consult.. (Please let there be log files!! haha). 

Here is my package:

```
      [ComVisible(true)]
    [PackageRegistration(UseManagedResourcesOnly = true)]
    [Description("A custom project type based on CPS")]
    [Guid(Guids.PackageGuid)]
    [ProvideMenuResource("Menus.ctmenu", 1)]
    [CodeGeneratorRegistration(typeof(AscxDesignerClassGenerator), "AscxDesignerClassGenerator", "{" + Guids.ProjectTypeGuid + "}", GeneratesDesignTimeSource = true)]
    [ProvideObject(typeof(AscxDesignerClassGenerator))]
    //[CodeGeneratorRegistration(typeof(AscxDesignerClassGenerator), "AscxDesignerClassGenerator", Guids.ProjectTypeGuid, GeneratesDesignTimeSource = true)]
    public sealed class VsPackage : Package
    {

```

Here is the generator:

```
 /// <summary>
    /// Summary description for ResourceKeysGenerator
    /// </summary>   
    [ComVisible(true)]
    [Guid(Guids.AscxDesignerGeneratorGuid)]
    [CodeGeneratorRegistration(typeof(AscxDesignerClassGenerator), "AscxDesignerClassGenerator", Guids.ProjectTypeGuid, GeneratesDesignTimeSource = true)]

    public class AscxDesignerClassGenerator : BaseCodeGeneratorWithSite
    {

```

**Comment by dazinator** [comment]
One question! 

I'd like to access the project properties from within my Generator. Is it possible to `Import` services into the Generator? If not, how do I access an instance of my `MyConfiguredProject` to get the properties?

Here is `MyConfiguredProject`

```

 [Export]
    [AppliesTo(MyUnconfiguredProject.UniqueCapability)]
    internal class MyConfiguredProject
    {
        [Import, SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "MEF")]
        internal ConfiguredProject ConfiguredProject { get; private set; }

        [Import, SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Justification = "MEF")]
        internal ProjectProperties Properties { get; private set; }
    }

```

How can I get to this instance from within the generator?

**Comment by dazinator** [comment]
In answer to my own question, managed to do this by getting the ConfiguredProject, and then resolving from it's services. 


```
            var project = projectItem.ContainingProject;
            var unconfiguredProject = project.GetUnconfiguredProject();
           var configuredProject = await unconfiguredProject.GetSuggestedConfiguredProjectAsync();
            var projectProps = configuredProject.Services.ProjectPropertiesProvider.GetCommonProperties();
```

**Pull request merged**
